package com.ustudents.fgen.gui;

import com.ustudents.fgen.FGen;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.scene.text.Font;
import javafx.scene.text.Text;
import javafx.scene.text.TextAlignment;

import java.util.Objects;

public class AboutWindow extends Window {
    public AboutWindow(double width, double height) {
        super(width, height);
    }

    @Override
    public void initialize() {
        GridPane gridPane = new GridPane();

        gridPane.setPadding(new Insets(16));

        Image image = new Image(Objects.requireNonNull(FGen.class.getResourceAsStream("/icon.png")));
        ImageView imageView = new ImageView(image);
        imageView.setFitHeight(96);
        imageView.setFitWidth(96);

        VBox vBox = new VBox();

        vBox.setPadding(new Insets(16));

        Label title = new Label("FGen (Fractal Generator)");
        title.setFont(new Font(16));
        title.setStyle("-fx-font-weight: bold");

        Label description = new Label("A tool to generate fractals based on\nvarious sets of parameters.\nFractals can be generated by providing a\nconfiguration file or through a GUI.");
        description.setPadding(new Insets(16, 0, 0, 0));

        Label authors = new Label("Made by Maxime Jauroyon and Hugo Kindel.");
        authors.setPadding(new Insets(16, 0, 0, 0));

        Label version = new Label("Version 1.0.0");
        version.setPadding(new Insets(16, 0, 0, 0));

        vBox.getChildren().add(title);
        vBox.getChildren().add(description);
        vBox.getChildren().add(authors);
        vBox.getChildren().add(version);

        gridPane.add(imageView, 0, 0);
        gridPane.add(vBox, 1, 0);

        setRoot(gridPane);
    }
}
