package com.ustudents.fgen.gui.views;

import com.ustudents.fgen.FGen;
import com.ustudents.fgen.gui.Window;
import javafx.geometry.Insets;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.VBox;
import javafx.scene.text.Font;

import java.util.Objects;

public class AboutWindow extends Window {
    GridPane root = new GridPane();

    public AboutWindow(double width, double height) {
        super(width, height);

        createRoot();

        setRoot(root);
    }

    public void createRoot() {
        root.setPadding(new Insets(16));

        Image image = new Image(Objects.requireNonNull(FGen.class.getResourceAsStream("/icon.png")));
        ImageView iconView = new ImageView(image);
        iconView.setFitHeight(96);
        iconView.setFitWidth(96);
        root.add(iconView, 0, 0);

        VBox contentBox = new VBox();
        contentBox.setPadding(new Insets(16));
        root.add(contentBox, 1, 0);

        Label title = new Label("FGen (Fractal Generator)");
        title.setFont(new Font(16));
        title.setStyle("-fx-font-weight: bold");
        contentBox.getChildren().add(title);

        Label description = new Label(
                """
                        A tool to generate fractals based on
                        various sets of parameters.
                        Fractals can be generated by providing a
                        configuration file or through a GUI.""");
        description.setPadding(new Insets(16, 0, 0, 0));
        contentBox.getChildren().add(description);

        Label authors = new Label("Made by Maxime Jauroyon and Hugo Kindel.");
        authors.setPadding(new Insets(16, 0, 0, 0));
        contentBox.getChildren().add(authors);

        Label version = new Label("Version 1.0.0");
        version.setPadding(new Insets(16, 0, 0, 0));
        contentBox.getChildren().add(version);
    }
}
